remote_theme: Phlow/feeling-responsive@gh-pages
title: Kacper Fleszar Garmin Watchfaces
description: A collection of watchfaces for Garmin smartwatches created by Kacper Fleszar.

plugins:
- jekyll-remote-theme
