remote_theme: chrisbobbe/jekyll-theme-prologue
title: kfleszar.dev
author: Kacper Fleszar
email: kacper.fleszar.dev@gmail.com
linkedin_url: https://www.linkedin.com/in/kacperfleszar/
avatar: assets/images/avatar.png
description: A collection of watchfaces for Garmin smartwatches created by Kacper Fleszar.
collections: [sections]

plugins:
- jekyll-remote-theme
